name: 'Pull Request Updater GitHub Action'
description: 'GitHub Action that updates a pull request with package version information'
author: 'Brice Molesti'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'edit-3'
  color: 'green'